environment:
  nodejs_version: "18"

branches:
  only:
    - main  # ветка git

cache: node_modules  # кеширование

install:
  - yarn add  # команда установки зависимостей

build: off  # отключаем встроенную в appveyor систему сборки

build_script:
  - yarn run build   # команда сборки

test_script:
  #- npm run lint && npm test && npm run coverage  # скрипт тестирования
  - yarn run lint # скрипт тестирования
